### ISSUE TITLE
Include more lessons on Algorithms

### ISSUE THREAD

**Issue by sonali623** [Techtonica/curriculum#1224]
Currently the lessons for only searching and sorting algorithms are available. Lessons on Greedy Algorithm, Backtracing Algorihtm, Divide and Conquer, Pattern Algorithm etc should also be added.

**Comment by sonali623** [comment]
@vegetabill I am a GSSoC 2020 participant and would like to work on this.

**Comment by Kundan28** [comment]
@vegetabill @alodahl I think this is a valid issue. Let's decide what should be the level of the issue, As per my knowledge there are many algorithms so this issue could be made as multiple contribution issue and it should be of `Hard` level.

**Comment by vegetabill** [comment]
Our curriculum is not geared towards Computer Science participants, so we actually intentionally keep our Algorithm & Data Structures list very short and only geared toward those commonly asked in technical interviews in the U.S. I am closing this as won't do.

@sonali623 thank you for the idea. If you are particularly interested in algorithms, I would suggest reviewing our existing lessons on them and see if you would like to improve them in a specific way, since we do not want to expand them.

**Comment by Kundan28** [comment]
Thanks for the clarification @vegetabill
