### ISSUE TITLE
Clear Instruction of Connecting Database

### ISSUE THREAD

**Issue by cadence09** [Techtonica/curriculum#1235]
https://github.com/Techtonica/curriculum/blob/master/projects/eventonica/eventonica-part6-postgres.md. 
From instruction step one to seven are clear and straight forward, but starting step 8 is confusing to me. My Postgres database is connected, but the SQL commends that I added to the Express didn't seem to connect to the database. If there is a more detailed instruction or an additional article link that will be helpful.

**Comment by vegetabill** [comment]
@cadence09 Step 8 is just asking you to confirm that queries run by your Express app save their changes to the database. If the database queries are succeeding, this should definitely be true. Maybe we need to add some troubleshooting notes. 

Are your DB queries being executed successfully? (their promises resolve, rather than reject)

**Comment by vegetabill** [comment]
@cadence09 do you think this is still useful? If not I will close.

**Comment by cadence09** [comment]
> @cadence09 do you think this is still useful? If not I will close.

@vegetabill It was my port issue. I have different port. Everything was running now. Yeah you can close the issue.
