### ISSUE TITLE
Advice for mobile development / react native topic outline

### ISSUE THREAD

**Issue by cadence09** [Techtonica/curriculum#1354]
I suggest to add a small sub-session for Firebase to this mobile development / react native topic outline, https://github.com/Techtonica/curriculum/blob/master/mobile-development/mobile-development.md. If an apprentice chooses to use Expo or React Native to build an app, Firebase would be a good option to use. It has built-in Oauth. It's very easy to use and to config with Expo. However, it would be confusing to use for a first-time user.  It would be nice to have some resources to help a first-time user to get some basic knowledge.

**Comment by vegetabill** [comment]
Firebase is a useful tool, @cadence09 but as it has its own docs I don't think Techtonica can really add much there. NoSQL options like Mongo were specifically de-emphasized because SQL is a must to know for interviews and future use. If you personally wanted to create a PR to add a list of resources you've found helpful, we could add that, but I'm not going to keep an issue for that as it's not a priority.
