### ISSUE TITLE
Fix JS testing using mocks lesson

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1361]
Fix the problems below, in the lesson: https://github.com/techtonica/curriculum/blob/main/testing-and-tdd/mocking-and-abstraction.md

## Problems found in the tutorial:

1. Materials:
Example video (10 min) -> This link goes to www.google.com. Its not an actual link to video

2. Other example article(20 min read) -> This article link goes to www.google.com. It does not go to an actual link. 

3. **Rewrite the following to help user better understand:**
Challenge
Following example above, try to represent the following scenarios and think about what would happen:
* Call getUser('not-octocat')?
* Change mockObject.id to be 42?
* Change mockObject.name to Techtonica?

**Change the explanation to:**
Challenge
Hope you were able to follow the example in the earlier section. Now, take a look at the following scenarios and see if you can make the changes: 
* Call getUser('not-octocat')?
* Change mockObject.id to be 42?
* Change mockObject.name to Techtonica?

4. Well, it's tricky because getTodo is still making an external call to the database which is difficult to handle. -> In this section, its hard to understand which database the author is pointing to. Readers may need more detail on the database and why making the external call is difficult and challenging. 

5. our reference TODO project) -> **typo**: our reference TODO project

6. It turns out that when we want to make complex verifications around how a mock is called doing that all manually is a lot of work... that somebody else has done for us. -> **This line is confusing. Need more simpler language explanation about the complex verification.** 

8. Independent Practice
It's an interesting task to implement your own mocking and validation code by hand and teaches you a lot of neat tricks. If you're feeling adventurous give that a try!
**The above section is not very helpful, and maybe redundant. Instead we can give link to example problems to practice on.**

**Comment by alodahl** [comment]
this is low priority, but there's no reason to close it.

**Comment by thisLinda** [comment]
Hi Alina, I have completed my work on Issue 1358 (have not written the report yet) and would like to be assigned to this issue as long as you're not in a hurry. I'm starting an intern position tomorrow and anticipate the next week or so I'll be furiously treading water. I did Jasmine testing while completing Udacity's front end nanodegree course.

**Comment by sasthan** [comment]
I would like to work on this task

**Comment by sasthan** [comment]
Problems that are in the tutorial:
1. Materials:
Example video (10 min) -> This link goes to www.google.com. Its not an actual link to video

2. Other example article(20 min read) -> This article link goes to www.google.com. It does not go to an actual link. 

3. **Rewrite the following to help user better understand:**
Challenge
Following example above, try to represent the following scenarios and think about what would happen:
* Call getUser('not-octocat')?
* Change mockObject.id to be 42?
* Change mockObject.name to Techtonica?

**Change the explanation to:**
Challenge
Hope you were able to follow the example in the earlier section. Now, take a look at the following scenarios and see if you can make the changes: 
* Call getUser('not-octocat')?
* Change mockObject.id to be 42?
* Change mockObject.name to Techtonica?

4. Well, it's tricky because getTodo is still making an external call to the database which is difficult to handle. -> In this section, its hard to understand which database the author is pointing to. Readers may need more detail on the database and why making the external call is difficult and challenging. 

5. our reference TODO project) -> **typo**: our reference TODO project

6. It turns out that when we want to make complex verifications around how a mock is called doing that all manually is a lot of work... that somebody else has done for us. -> **This line is confusing. Need more simpler language explanation about the complex verification.** 

8. Independent Practice
It's an interesting task to implement your own mocking and validation code by hand and teaches you a lot of neat tricks. If you're feeling adventurous give that a try!
**The above section is not very helpful, and maybe redundant. Instead we can give link to example problems to practice on.**

**Comment by severinrudie** [comment]
>     1. Materials:
>        Example video (10 min) -> This link goes to [www.google.com](http://www.google.com). Its not an actual link to video
> 
>     2. Other example article(20 min read) -> This article link goes to [www.google.com](http://www.google.com). It does not go to an actual link.

Are there specific resources to which these are supposed to link?  Or is part of this story finding new ones?

**Comment by alodahl** [comment]
@severinrudie no, whoever made this file never changed the template.

**Comment by alodahl** [comment]
Here's an example if a good Materials section: https://github.com/Techtonica/curriculum/blob/main/web/css.md

**Comment by alodahl** [comment]
remaining issues moved to #1584. the rest are resolved.
