### ISSUE TITLE
Restyle "Building Confidence" slideshow using proper format

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#1362]
https://docs.google.com/presentation/d/1EauFdEp4UJcBK50ioj-giPwFeWf2FHc7i_rn0XGf5f8/edit?usp=sharing

- [ ] format the above slideshow to the [2020 Slides Template](https://docs.google.com/presentation/d/1uFlV8eVrPtwjb4wPoUCd7Fk3PNqf1Eoo9mZ-_7D3_GQ/edit#slide=id.p) standards.  Make a copy to your own drive to have access to the styles.
- [ ] Please also make sure it follows the style rules described here: #600 

- [ ] Once you've completed this, make a PR of any typo in this project, and link this issue in the PR to receive GSSoC points.
For FAQs on how to contribute, see: https://github.com/Techtonica/curriculum#volunteering

**Comment by HeroicHitesh** [comment]
@alodahl I am interested in this task, please assign this issue to me.

**Comment by alodahl** [comment]
Thanks @HeroicHitesh !   If this is your first Techtonica contribution, be sure to follow these directions and then you can start: https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md

**Comment by HeroicHitesh** [comment]
Thanks, @alodahl for assigning the task. Yes, it's my first Techtonica contribution, I have filled the forms and read the guidelines. I am going to start working now.

**Comment by HeroicHitesh** [comment]
@alodahl made the changes as per #600 and [2020 Slides Template](https://docs.google.com/presentation/d/1uFlV8eVrPtwjb4wPoUCd7Fk3PNqf1Eoo9mZ-_7D3_GQ/edit#slide=id.p). Can you check once this [copy](https://docs.google.com/presentation/d/1iiSXs_I2H5m6bhXfeJyZi5sJCyXGZyd1PVqJdKzJBPk/edit?usp=sharing) so that I can transfer the ownership and open a PR? Or should I open a PR directly and we can have a discussion over there?

**Comment by HeroicHitesh** [comment]
@alodahl Found the file to edit. Created PR. Check and merge if found suitable else explain corrections to be made.
