### ISSUE TITLE
Improvement for instructions on installing node.js

### ISSUE THREAD

**Issue by aedward8** [Techtonica/curriculum#1515]
https://github.com/Techtonica/curriculum/blob/main/node-js/node-lab-exercise-part-1.md

install with Brew or instructions in read me

These instructions don't go with the instructions in the readme. I tried to do both and it kinda mess things up. Eventually just went with what was exactly in the the readme so maybe makes sense to se updates these instructions to that? Also I didn't have permissions to with brew to download nvm so that threw a lot of errors and issues for me.

**Comment by vegetabill** [comment]
Closing as won't fix. IIRC, this issue was specific to misconfigured homebrew which was reported to Techtonica IT who sets up the laptops and so they should figure it out. Issues of this type also should have plenty of StackOverflow topics on them. Maybe we shouldn't even try to duplicate all our own instructions here.

Although confusing, if homebrew is set up right, it is okay to have both nvm and brew-based node.
