### ISSUE TITLE
Add info to 2 slides in the Data Models slideshow, find a video

### ISSUE THREAD

**Issue by alodahl** [Techtonica/curriculum#454]
- you can find the lesson slides [in this file](https://docs.google.com/presentation/d/19XTnwuzk11SaE0Kgn0R0t_nvQ_1L0j_Tk-AdwfcsiTg/edit?usp=sharing).

- [ ] Add more information on the Types of Data Models slide
- [ ] Review the slide deck (Agenda slide may also need some more editing)
- [ ] Find or record an explanatory video, and add the link to the "materials" section in the[Data Models topic outline](https://github.com/Techtonica/curriculum/blob/master/databases/data-models.md).

Part of issue #419
Immediately follows Express.js lesson

**Comment by alyssawhitwell** [comment]
@MichelleGlauser -- @cwbane and I were able to make the majority of the Data Models deck (see https://docs.google.com/presentation/d/19XTnwuzk11SaE0Kgn0R0t_nvQ_1L0j_Tk-AdwfcsiTg/edit?usp=sharing)

However, we would still want someone to do the following:
- [ ] Add more information on the Types of Data Models slide
- [ ] Review the slide deck (Agenda slide may also need some more editing)

before this issue is considered complete. Thanks!
cc @wolkenrausch

**Comment by jdq22** [comment]
I reviewed the slide deck, and I think it's fantastic! I also added links to articles about each data model on the "Types of data models" slide.

What I'd do next is:
- [ ] Add slides on why someone would want to use each type of data model.
