### ISSUE TITLE
Recipe-page: Initialize recipe-page folder instead of techtonica-projects folder as git repo

### ISSUE THREAD

**Issue by isabelleyiu** [Techtonica/curriculum#518]
As @judytuna  and I discussed earlier, under the Setup Instructions for the recipe-page project, we were asked to initialize "techtonica-projects" folder as a single git repo. Instead, we should create a git repo for each of the project folder that we are going to create under "techtonica-projects", such as the "recipe-page".

**Comment by judytuna** [comment]
Lessons that build on this also use the `techtonica-projects` folder, so we
should rename it in all the lessons to something else such as `git-lesson`
maybe! This is not urgent, and we shouldn't change it today because several
apprentices are already partway through the git lessons; this is a note to
fix it before the next cohort // note-to-self to explain to current cohort
that making a projectS folder i to a git repo is an antipattern!

Thanks!

**Comment by alodahl** [comment]
I agree, there's no need to initialize "techtonica-projects"... I think the intention was to initialize recipe-page. I've addressed Isabelle's issue, and I will make sure other files are consistent next.

**Comment by alodahl** [comment]
I changed the recipe page parts 1 and 2 so that recipe-page is the git repo, not techtonica-projects.
